name: Model Training and Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install deepchecks seaborn pandas numpy matplotlib scikit-learn mlflow xgboost hyperopt


      - name: Upload Artifacts 
        uses: actions/upload-artifact@v2
        with: 
            name: wine_data
            path: wine_quality_training/wine_data/train_wine_data.csv
                  wine_quality_training/wine_data/test_wine_data.csv
                  
    #   - name: Download Artifacts
    #     uses: actions/download-artifact@v2
    #     with:
    #       name: wine_data 
    #       path: wine_quality_training/wine_data/train_wine_data.csv
    #             wine_quality_training/wine_data/test_wine_data.csv

      - name: Train Model
        run: python wine_quality_training/wine_training.py

      - name: Validate Model Performance
        run: python experiment_tracking/wine-tracking.py

      - name: Archive Deepchecks Results
        uses: actions/upload-artifact@v3
        with:
          name: deepchecks results
          path: experiment_tracking/mlruns/1/2b885cabc1f8435dbdd6c684891242ac/artifacts/model/MLmodel
